using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Runtime.InteropServices;
using System.Text;
using Entitas;
using Entitas.Generic;
using MERunner;
using Ent = Entitas.Generic.Entity<Main>;

namespace GenEntitas
{
[Export(typeof(ISystem_Factory))]
public sealed class Factory_PostProcAddFileHeaderSystem : TSystem_Factory<PostProcAddFileHeaderSystem> {  }

	[Guid("93E843A5-D1F0-4F8E-825C-D5627635ADF7")]
	public class PostProcAddFileHeaderSystem : ReactiveSystem<Ent>
	{
		public				PostProcAddFileHeaderSystem				(  ) : this( Hub.Contexts )
		{
		}

		public				PostProcAddFileHeaderSystem				( Contexts contexts ) : base( contexts.Get<Main>() )
		{
		}

		private const		String					TEMPLATE				=
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ${GeneratedBy}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

		protected override	ICollector<Ent>			GetTrigger				( IContext<Ent> context )
		{
			return context.CreateCollector( Matcher_<Main,GeneratedFileComp>.I );
		}

		protected override	Boolean					Filter					( Ent entity )
		{
			return entity.Has_<GeneratedFileComp>();
		}

		protected override	void					Execute					( List<Ent> entities )
		{
			foreach ( var ent in entities )
			{
				var stringBuilder = new StringBuilder( TEMPLATE.Replace("${GeneratedBy}", ent.Get_<GeneratedFileComp>().GeneratedBy) );
				stringBuilder.Append( ent.Get_<GeneratedFileComp>().Contents );
				ent.Replace_( new GeneratedFileComp(
					ent.Get_<GeneratedFileComp>().FilePath,
					stringBuilder.ToString(  ),
					ent.Get_<GeneratedFileComp>().GeneratedBy ) );
			}
		}
	}
}